# -*- coding: utf-8 -*-
"""ProyectoFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTutMLMHd2_Orhjq5ZErqbQ0pJPzoFiy

# Proyecto: Brechas de genero en las carreras STEM en las universidades de pererira

# Resumen del proyecto

Este proyecto analiza las brechas de género en las carreras STEM (Ciencia, Tecnología, Ingeniería y Matemáticas) de las universidades de Pereira mediante técnicas de análisis y ciencia de datos. A partir de información institucional sobre matrícula, deserción y graduación, se evidenció una baja participación femenina en programas de ingeniería y tecnología. Los resultados muestran que, aunque las mujeres representan una parte importante del estudiantado, persisten desigualdades en acceso y permanencia. Se propone fortalecer las políticas universitarias con programas de mentoría, becas y sensibilización sobre equidad de género. El estudio concluye que cerrar las brechas en las áreas STEM es clave para promover una educación superior más inclusiva y equitativa en la región.

# Preguntas a responder

1) Identificar el año con mayor número de personas inscritas en los programas académicos analizados.

2) Determinar la carrera con mayor número de mujeres en cada año del periodo de estudio.

3) Analizar la evolución de la participación relativa de mujeres y hombres a lo largo de los años, evaluando si la brecha de género se reduce, aumenta o se mantiene.

4) Examinar en qué etapa del proceso académico (inscripción, admisión o matrícula ) se amplía con mayor intensidad la brecha de género.

5) Comparar los programas académicos para identificar aquellos que presentan las mayores diferencias de género, tanto en favor de los hombres como de las mujeres.

***el proyecto busca mostrar cómo evoluciona la brecha de género a lo largo del proceso académico, incluyendo la inscripcion, la matricula y los admitidos, con indicadores claros y visualizaciones que evidencien si la participación femenina se mantiene, crece o disminuye.***

# preparacion e importacion de datos
"""

#librerias para los codigos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

#importamos todas las librerias
INS = pd.read_csv(r'/content/drive/MyDrive/dataframe/CONSOLIDADO INSCRITOS.csv', delimiter=';')
ADM = pd.read_csv(r'/content/drive/MyDrive/dataframe/CONSOLIDADO ADMITIDOS.csv', delimiter=';')
MATR = pd.read_csv(r'/content/drive/MyDrive/dataframe/CONSOLIDADO MATRICULADOS.csv', delimiter=';')

from google.colab import drive
drive.mount('/content/drive')

"""# INSCRITOS

$Limpieza$
"""

#mostrar primero los 10 primeros datos de los inscritos
print(INS.head(5))

#cambiamos el nombre de la columna MUNICIPIO DE DOMICILIO DE LA IES

INS.rename(columns={'MUNICIPIO DE DOMICILIO DE LA IES': 'MUNICIPIO'},
           inplace=True)
print(INS.columns)

#eliminar Santa Rosa de cabal y sus datos

# Crear máscara para quitar Santa Rosa de Cabal en todas sus formas
Mascara = ~INS['MUNICIPIO'].isin(['Santa Rosa de Cabal', 'Santa Rosa d'])
Base_inscritos = INS[Mascara]

print(Base_inscritos['MUNICIPIO'].value_counts())
print("\n")

# Reemplazar Masculino/Femenino por Hombre/Mujer
Base_inscritos['SEXO'] = Base_inscritos['SEXO'].replace({
    'Masculino': 'Hombre',
    'Femenino': 'Mujer'
})

# Verificar cambios
print(Base_inscritos['SEXO'])

"""$Analisis$"""

#Estadísticas descriptivas

Estadistica = Base_inscritos.describe().astype(int)
print(Estadistica, "\n")

media = Base_inscritos.select_dtypes(include=np.number).mean().astype(int)
print("media\n", media, "\n")

mediana = Base_inscritos.select_dtypes(include=np.number).median().astype(int)
print("mediana\n", mediana, "\n")

moda = Base_inscritos.select_dtypes(include=np.number).mode().astype(int)
print("moda\n", moda, "\n")

# ¿Cuántos hombres y mujeres hay inscritos en total?

print("la cantidad de estudiantes es de:", Base_inscritos['SEXO'].value_counts().sum())
print(Base_inscritos['SEXO'].value_counts())

#Porcentaje de hombres y mujeres Inscritos

total_Ins = Base_inscritos['SEXO'].value_counts().sum()
mujeres_Ins = Base_inscritos['SEXO'].value_counts().get('Mujer', 0)
hombres_Ins = Base_inscritos['SEXO'].value_counts().get('Hombre', 0)

pct_mujeres_adm = (mujeres_Ins / total_Ins) * 100
pct_hombres_adm = (hombres_Ins / total_Ins) * 100

print("Porcentaje de mujeres y hombres entre los admitidos:")
print(f"→ Mujeres admitidas: {pct_mujeres_adm:.2f}%")
print(f"→ Hombres admitidos: {pct_hombres_adm:.2f}%")

"""$visualizaciones$"""

# Agrupamos inscritos por programa y sexo
programa_counts = Base_inscritos.groupby(["PROGRAMA ACADÉMICO","SEXO"])["INSCRITOS"].sum().unstack(fill_value=0)

# Seleccionamos los 15 programas con más inscritos
top_programas = programa_counts.sum(axis=1).sort_values(ascending=False).head(15)
programa_counts = programa_counts.loc[top_programas.index, ["Hombre","Mujer"]]

# Calculamos porcentajes por programa
programa_pct = programa_counts.div(programa_counts.sum(axis=1), axis=0) * 100

# Convertimos a formato largo para Plotly
programa_pct_reset = programa_pct.reset_index().melt(id_vars="PROGRAMA ACADÉMICO",
                                                     value_vars=["Hombre","Mujer"],
                                                     var_name="Sexo", value_name="Porcentaje")

# Gráfico interactivo
fig = px.bar(programa_pct_reset,
             x="PROGRAMA ACADÉMICO",
             y="Porcentaje",
             color="Sexo",
             barmode="group",
             color_discrete_map={"Hombre": "steelblue", "Mujer": "orange"},
             text="Porcentaje")

fig.update_traces(texttemplate='%{text:.0f}%', textposition='outside')

fig.update_layout(title="Comparativa Hombres vs Mujeres por Programa Académico (Top 10)",
                  xaxis_title="Programa Académico",
                  yaxis_title="Porcentaje dentro del programa (%)",
                  xaxis_tickangle=-45,
                  legend_title="Sexo",
                  bargap=0.15)

fig.show()

# Agrupar inscritos por año y sexo
evolucion = Base_inscritos.groupby(["AÑO", "SEXO"])["INSCRITOS"].sum().reset_index()

# Calcular participación relativa (% mujeres y % hombres por año)
totales = evolucion.groupby("AÑO")["INSCRITOS"].transform("sum")
evolucion["Porcentaje"] = (evolucion["INSCRITOS"] / totales) * 100

# Gráfico interactivo
fig = px.line(evolucion,
              x="AÑO",
              y="Porcentaje",
              color="SEXO",
              markers=True,
              color_discrete_map={"Hombre": "blue", "Mujer": "orange"},
              title="Tendencia de participación femenina vs masculina en el tiempo")

fig.update_traces(mode="lines+markers", line=dict(width=3))
fig.update_layout(yaxis_title="Participación (%)", xaxis_title="Año")
fig.show()

"""# ADMITIDOS

$Limpieza$
"""

print(ADM.head(5))

#cambio de nombre de columna

print(ADM.columns)

print("\n")
ADM = ADM.rename(columns={'MUNICIPIO DE DOMICILIO DE LA IES': 'MUNICIPIO'})
print(ADM.columns, "\n")

INS['MUNICIPIO'] = INS['MUNICIPIO'].replace({
    'Pereira ': 'Pereira',   # por si hay espacio al final
    'PEREIRA': 'Pereira',
    'pereira': 'Pereira'
})

print(INS['MUNICIPIO'].value_counts())
print("\n")

# ----- ELIMINAR TODAS LAS VARIANTES DE SANTA ROSA -----
print("------ Antes de la eliminación de Santa Rosa -----")
print(ADM['MUNICIPIO'].value_counts())


Mascara = ~ADM['MUNICIPIO'].isin(['Santa Rosa de Cabal', 'Santa Rosa d', 'Santa Rosa De Cabal', 'SANTA ROSA DE CABAL'])
Base_admitidos = ADM[Mascara]

print("\n------ Después de la eliminación de Santa Rosa -----")
print(Base_admitidos['MUNICIPIO'].value_counts())

#unificar los pereiras

print("\n------ Antes de la unificación de Pereira -----")
print(Base_admitidos['MUNICIPIO'].value_counts())

Base_admitidos['MUNICIPIO'] = Base_admitidos['MUNICIPIO'].replace({
    'Pereira ': 'Pereira',
    'PEREIRA': 'Pereira',
    'pereira': 'Pereira'
})

print("\n------ Después de la unificación de Pereira -----")
print(Base_admitidos['MUNICIPIO'].value_counts())

# Reemplazar Masculino/Femenino por Hombre/Mujer
Base_admitidos['SEXO'] = Base_admitidos['SEXO'].replace({
    'Masculino': 'Hombre',
    'HOMBRE': 'Hombre',
    'Femenino': 'Mujer',
    'MUJER': 'Mujer'
})

# Verificar cambios
print(Base_admitidos['SEXO'].value_counts())

"""$analisis$"""

#estadistica Descriptiva

Estadistica = Base_admitidos.describe().astype(int)
print(Estadistica, "\n")

media = Base_admitidos.select_dtypes(include=np.number).mean().astype(int)
print("media\n", media, "\n")

mediana = Base_admitidos.select_dtypes(include=np.number).median().astype(int)
print("mediana\n", mediana, "\n")

moda = Base_admitidos.select_dtypes(include=np.number).mode().astype(int)
print("moda\n", moda, "\n")

#Contar cuántos hombres y cuántas mujeres se matricularon.

print("La cantidad de Hombres y mujeres que se matricularon fueron de:", Base_admitidos['SEXO'].value_counts().sum())
print(Base_admitidos['SEXO'].value_counts())

# Comparar % mujeres admitidas vs % mujeres Admitidas.

total_adm = Base_admitidos['SEXO'].value_counts().sum()
mujeres_adm = Base_admitidos['SEXO'].value_counts().get('Mujer', 0)
hombres_adm = Base_admitidos['SEXO'].value_counts().get('Hombre', 0)

pct_mujeres_adm = (mujeres_adm / total_adm) * 100
pct_hombres_adm = (hombres_adm / total_adm) * 100

print("Porcentaje de mujeres y hombres entre los admitidos:")
print(f"→ Mujeres admitidas: {pct_mujeres_adm:.2f}%")
print(f"→ Hombres admitidos: {pct_hombres_adm:.2f}%")

#exportar el dataset

"""$visualizaciones$"""

# --- Gráfico de barras: Hombres vs Mujeres Admitidos ---
data_hm = pd.DataFrame({
    'Sexo': ['Hombre', 'Mujer'],
    'Porcentaje': [
        (Base_admitidos['SEXO'].value_counts().get('Hombre', 0) / Base_admitidos['SEXO'].value_counts().sum()) * 100,
        (Base_admitidos['SEXO'].value_counts().get('Mujer', 0) / Base_admitidos['SEXO'].value_counts().sum()) * 100
    ]
})

fig = px.bar(
    data_hm,
    x='Sexo',
    y='Porcentaje',
    color='Sexo',
    text='Porcentaje',
    color_discrete_map={'Hombre': 'steelblue', 'Mujer': 'orange'},
    title='Comparación Hombres vs Mujeres Admitidos'
)

fig.update_traces(texttemplate='%{text:.0f}%', textposition='outside')
fig.update_layout(
    yaxis_title='Porcentaje (%)',
    xaxis_title='Sexo',
    bargap=0.3,
    showlegend=False
)
fig.show()

# --- Gráfico de evolución: Hombres y Mujeres Admitidos por Año ---
Base_admitidos['AÑO'] = pd.to_numeric(Base_admitidos['AÑO'], errors='coerce')
evolucion_adm = Base_admitidos.groupby(["AÑO", "SEXO"])["ADMITIDOS"].sum().reset_index()
totales_anuales = evolucion_adm.groupby("AÑO")["ADMITIDOS"].transform("sum")
evolucion_adm["Porcentaje"] = (evolucion_adm["ADMITIDOS"] / totales_anuales) * 100

fig = px.line(
    evolucion_adm,
    x="AÑO",
    y="Porcentaje",
    color="SEXO",
    markers=True,
    color_discrete_map={"Hombre": "steelblue", "Mujer": "orange"},
    title="Evolución de la participación de Hombres y Mujeres Admitidos por Año"
)

fig.update_traces(mode="lines+markers", line=dict(width=3))
fig.update_layout(
    yaxis_title="Porcentaje dentro del año (%)",
    xaxis_title="Año",
    legend_title="Sexo",
    hovermode="x unified"
)
fig.show()

# --- CARRERA CON MÁS ADMITIDOS POR GÉNERO (Donut Chart) ---

# Calculate top 10 programs for women and men based on admitted students
admitidos_genero = Base_admitidos.groupby(["PROGRAMA ACADÉMICO", "SEXO"])["ADMITIDOS"].sum().reset_index()

top_mujer = admitidos_genero[admitidos_genero['SEXO'] == 'Mujer'].nlargest(15, 'ADMITIDOS')


# Mujeres
fig_mujer = px.pie(
    top_mujer,
    names='PROGRAMA ACADÉMICO',
    values='ADMITIDOS',
    hole=0.4,
    title='Top 15 Carreras con Más Mujeres Admitidas',
    color_discrete_sequence=px.colors.sequential.Oranges
)
fig_mujer.show()

top_hombre = admitidos_genero[admitidos_genero['SEXO'] == 'Hombre'].nlargest(15, 'ADMITIDOS')

# Hombre
fig_hombre = px.pie(
    top_hombre,
    names='PROGRAMA ACADÉMICO',
    values='ADMITIDOS',
    hole=0.4,
    title='Top 15 Carreras con Más Hombres Admitidos',
    color_discrete_sequence=px.colors.sequential.Blues
)
fig_hombre.show()

# Agrupamos admitidos por programa y sexo
programa_counts_adm = Base_admitidos.groupby(["PROGRAMA ACADÉMICO","SEXO"])["ADMITIDOS"].sum().unstack(fill_value=0)

# Seleccionamos los 15 programas con más admitidos
top_programas_adm = programa_counts_adm.sum(axis=1).sort_values(ascending=False).head(15)
programa_counts_adm = programa_counts_adm.loc[top_programas_adm.index, ["Hombre","Mujer"]]

# Calculamos porcentajes por programa
programa_pct_adm = programa_counts_adm.div(programa_counts_adm.sum(axis=1), axis=0) * 100

# Convertimos a formato largo para Plotly
programa_pct_reset_adm = programa_pct_adm.reset_index().melt(id_vars="PROGRAMA ACADÉMICO",
                                                     value_vars=["Hombre","Mujer"],
                                                     var_name="Sexo", value_name="Porcentaje")

# Gráfico interactivo
fig_adm = px.bar(programa_pct_reset_adm,
             x="PROGRAMA ACADÉMICO",
             y="Porcentaje",
             color="Sexo",
             barmode="group",
             color_discrete_map={"Hombre": "steelblue", "Mujer": "orange"},
             text="Porcentaje")

fig_adm.update_traces(texttemplate='%{text:.0f}%', textposition='outside')

fig_adm.update_layout(title="Comparativa Hombres vs Mujeres por Programa Académico (Admitidos - Top 15)",
                  xaxis_title="Programa Académico",
                  yaxis_title="Porcentaje dentro del programa (%)",
                  xaxis_tickangle=-45,
                  legend_title="Sexo",
                  bargap=0.15)

fig_adm.show()

"""# MATRICULADOS

$limpieza$
"""

#mostrar primero los 10 primeros datos de los inscritos
print(MATR.head(5))

#cambiamos el nombre de la columna MUNICIPIO DE DOMICILIO DE LA IES

MATR.rename(columns={'MUNICIPIO DE DOMICILIO DE LA IES': 'MUNICIPIO',
                     'MATRICULADOS ': 'MATRICULADOS'},
           inplace=True)
print(MATR.columns)

#eliminar Santa Rosa de cabal y sus datos

# Crear máscara para quitar Santa Rosa de Cabal en todas sus formas
Mascara = ~MATR['MUNICIPIO'].isin(['Santa Rosa de Cabal', 'Santa Rosa d', 'Santa Rosa De Cabal', 'SANTA ROSA DE CABAL'])
Base_Matriculados = MATR[Mascara]

# Strip whitespace from column names
Base_Matriculados.columns = Base_Matriculados.columns.str.strip()

print(Base_Matriculados['MUNICIPIO'].value_counts())
print("\n")
print(Base_Matriculados.columns) # Print columns to verify the name

# Reemplazar Masculino/Femenino por Hombre/Mujer

Base_Matriculados = Base_Matriculados.copy()
Base_Matriculados['SEXO'] = Base_Matriculados['SEXO'].replace({
    'Masculino': 'Hombre',
    'MASculino': 'Hombre',
    'HOMBRE': 'Hombre',
    'Femenino': 'Mujer',
    'FEMENINO': 'Mujer',
    'MUJER': 'Mujer'
})

# Verify changes
print(Base_Matriculados['SEXO'].value_counts())

# Eliminamos posibles espacios extra en nombres de columnas
Base_Matriculados.columns = Base_Matriculados.columns.str.strip()

print(Base_Matriculados.columns)

"""$Analisis$"""

#estadistica Descriptiva

Estadistica = Base_Matriculados.describe().astype(int)
print(Estadistica, "\n")

media = Base_Matriculados.select_dtypes(include=np.number).mean().astype(int)
print("media\n", media, "\n")

mediana = Base_admitidos.select_dtypes(include=np.number).median().astype(int)
print("mediana\n", mediana, "\n")

moda = Base_admitidos.select_dtypes(include=np.number).mode().astype(int)
print("moda\n", moda, "\n")

#cantidad de estudiantes matriculados
print("la cantidad de estudiantes es de:", Base_Matriculados['SEXO'].value_counts().sum())
print(Base_Matriculados['SEXO'].value_counts())

total_Ins = Base_Matriculados['SEXO'].value_counts().sum()
mujeres_Ins = Base_Matriculados['SEXO'].value_counts().get('Mujer', 0)
hombres_Ins = Base_Matriculados['SEXO'].value_counts().get('Hombre', 0)

pct_mujeres_matric = (mujeres_Ins / total_Ins) * 100
pct_hombres_matric = (hombres_Ins / total_Ins) * 100

print("Porcentaje de mujeres y hombres entre los admitidos:")
print(f"→ Mujeres admitidas: {pct_mujeres_adm:.2f}%")
print(f"→ Hombres admitidos: {pct_hombres_adm:.2f}%")

"""$visualizaciones$"""

# --- Gráfico de evolución: Hombres y Mujeres Admitidos por Año ---
Base_Matriculados['AÑO'] = pd.to_numeric(Base_Matriculados['AÑO'], errors='coerce')
evolucion_matric = Base_Matriculados.groupby(["AÑO", "SEXO"])["MATRICULADOS"].sum().reset_index()
totales_anuales = evolucion_matric.groupby("AÑO")["MATRICULADOS"].transform("sum")
evolucion_matric["Porcentaje"] = (evolucion_matric["MATRICULADOS"] / totales_anuales) * 100

fig = px.line(
    evolucion_matric,
    x="AÑO",
    y="Porcentaje",
    color="SEXO",
    markers=True,
    color_discrete_map={"Hombre": "steelblue", "Mujer": "orange"},
    title="Evolución de la participación de Hombres y Mujeres Matriculados por Año"
)

fig.update_traces(mode="lines+markers", line=dict(width=3))
fig.update_layout(
    yaxis_title="Porcentaje dentro del año (%)",
    xaxis_title="Año",
    legend_title="Sexo",
    hovermode="x unified"
)
fig.show()

# --- CARRERA CON MÁS ADMITIDOS POR GÉNERO (Donut Chart) ---

# Calcular total de matriculados por programa y sexo
matriculados_genero = (
    Base_Matriculados
    .groupby(["PROGRAMA ACADÉMICO", "SEXO"])["MATRICULADOS"]
    .sum()
    .reset_index()
)

# Filtrar y ordenar top 10 mujeres
top_mujer = (
    matriculados_genero[matriculados_genero['SEXO'] == 'Mujer']
    .sort_values(by='MATRICULADOS', ascending=False)
    .head(10)
)

# Gráfico tipo donut
fig_mujer = px.pie(
    top_mujer,
    names='PROGRAMA ACADÉMICO',
    values='MATRICULADOS',
    hole=0.4,
    title=' Top 15 Carreras con Más Mujeres Matriculadas 👩',
    color_discrete_sequence=px.colors.sequential.Oranges
)

fig_mujer.show()

top_hombre_matriculados = matriculados_genero[matriculados_genero['SEXO'] == 'Hombre'].nlargest(15, 'MATRICULADOS')


# Hombre
fig_hombre = px.pie(
    top_hombre_matriculados,
    names='PROGRAMA ACADÉMICO',
    values='MATRICULADOS',
    hole=0.4,
    title='Top 15 Carreras con Más Hombres Matriculadas',
    color_discrete_sequence=px.colors.sequential.Blues
)
fig_hombre.show()

# Agrupamos matriculados por programa y sexo
programa_counts_matric = Base_Matriculados.groupby(["PROGRAMA ACADÉMICO","SEXO"])["MATRICULADOS"].sum().unstack(fill_value=0)

# Seleccionamos los 15 programas con más matriculados
top_programas_matric = programa_counts_matric.sum(axis=1).sort_values(ascending=False).head(15)
programa_counts_matric = programa_counts_matric.loc[top_programas_matric.index, ["Hombre","Mujer"]]

# Calculamos porcentajes por programa
programa_pct_matric = programa_counts_matric.div(programa_counts_matric.sum(axis=1), axis=0) * 100

# Convertimos a formato largo para Plotly
programa_pct_reset_matric = programa_pct_matric.reset_index().melt(id_vars="PROGRAMA ACADÉMICO",
                                                     value_vars=["Hombre","Mujer"],
                                                     var_name="Sexo", value_name="Porcentaje")

# Gráfico interactivo
fig_matric = px.bar(programa_pct_reset_matric,
             x="PROGRAMA ACADÉMICO",
             y="Porcentaje",
             color="Sexo",
             barmode="group",
             color_discrete_map={"Hombre": "steelblue", "Mujer": "orange"},
             text="Porcentaje")

fig_matric.update_traces(texttemplate='%{text:.0f}%', textposition='outside')

fig_matric.update_layout(title="Comparativa Hombres vs Mujeres por Programa Académico (Matriculados - Top 15)",
                  xaxis_title="Programa Académico",
                  yaxis_title="Porcentaje dentro del programa (%)",
                  xaxis_tickangle=-45,
                  legend_title="Sexo",
                  bargap=0.15)

fig_matric.show()

"""# INSCRITOS - ADMITIDOS - MATRICULADOS

"""

# Calcular el porcentaje de mujeres y hombres en cada base

# --- Inscritos ---
total_inscritos = len(Base_inscritos)
pct_mujeres_Ins = (Base_inscritos['SEXO'].str.lower().eq('mujer').sum() / total_inscritos) * 100
pct_hombres_Ins = (Base_inscritos['SEXO'].str.lower().eq('hombre').sum() / total_inscritos) * 100

# --- Admitidos ---
total_admitidos = len(Base_admitidos)
pct_mujeres_adm = (Base_admitidos['SEXO'].str.lower().eq('mujer').sum() / total_admitidos) * 100
pct_hombres_adm = (Base_admitidos['SEXO'].str.lower().eq('hombre').sum() / total_admitidos) * 100


# --- Matriculados ---
total_matriculados = len(Base_Matriculados)
pct_mujeres_Matr = (Base_Matriculados['SEXO'].str.lower().eq('mujer').sum() / total_matriculados) * 100
pct_hombres_Matr = (Base_Matriculados['SEXO'].str.lower().eq('hombre').sum() / total_matriculados) * 100

print("---Inscritos---")
print(f"porcentaje de Hombres Inscritos: {pct_hombres_Ins:.2f}%")
print(f"porcentaje de Mujeres Inscritas: {pct_mujeres_Ins:.2f}%")

print("\n---Matriculados---")
print(f"porcentaje de Hombres Matriculados: {pct_hombres_Matr:.2f}%")
print(f"porcentaje de Mujeres Matriculados: {pct_mujeres_Matr:.2f}%")

print("\n---Admitidos---")
print(f"porcentaje de Hombres Admitidos: {pct_hombres_adm:.2f}%")
print(f"porcentaje de Mujeres Admitidas: {pct_mujeres_adm:.2f}%")

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Datos dinámicos desde tus variables
categorias = ['Inscritos', 'Admitidos', 'Matriculados']
mujeres = [pct_mujeres_Ins, pct_mujeres_adm, pct_mujeres_Matr]
hombres = [pct_hombres_Ins, pct_hombres_adm, pct_hombres_Matr]

# Cerrar el radar (volver al inicio)
categorias += [categorias[0]]
mujeres += [mujeres[0]]
hombres += [hombres[0]]

# Subplots: Mujeres y Hombres
fig = make_subplots(
    rows=1, cols=2,
    specs=[[{'type': 'polar'}, {'type': 'polar'}]],
    subplot_titles=('Mujeres', 'Hombres')
)

fig.add_trace(go.Scatterpolar(
    r=mujeres, theta=categorias, fill='toself',
    name='Mujeres', line=dict(color='orange'),
    hovertemplate='%{theta}: %{r:.2f}%<extra></extra>'
), row=1, col=1)

fig.add_trace(go.Scatterpolar(
    r=hombres, theta=categorias, fill='toself',
    name='Hombres', line=dict(color='blue'),
    hovertemplate='%{theta}: %{r:.2f}%<extra></extra>'
), row=1, col=2)

fig.update_layout(
    title_text='Comparación porcentual por género y etapa',
    template='plotly_dark', height=600, width=1200, showlegend=False
)

for i in range(1, 3):
    fig.update_polars(
        radialaxis=dict(visible=True, range=[40, 55]),
        row=1, col=i
    )

fig.show()

# Datos dinámicos desde tus variables
categorias = ['Inscritos', 'Admitidos', 'Matriculados']
mujeres = [pct_mujeres_Ins, pct_mujeres_adm, pct_mujeres_Matr]
hombres = [pct_hombres_Ins, pct_hombres_adm, pct_hombres_Matr]

# Cerrar el radar (volver al inicio)
categorias += [categorias[0]]
mujeres += [mujeres[0]]
hombres += [hombres[0]]

# Crear figura única con ambos géneros
fig = go.Figure()

fig.add_trace(go.Scatterpolar(
    r=mujeres,
    theta=categorias,
    fill='toself',
    name='Mujeres',
    line=dict(color='orange', width=3),
    hovertemplate='%{theta}: %{r:.2f}%<extra></extra>'
))

fig.add_trace(go.Scatterpolar(
    r=hombres,
    theta=categorias,
    fill='toself',
    name='Hombres',
    line=dict(color='blue', width=3),
    hovertemplate='%{theta}: %{r:.2f}%<extra></extra>'
))

# Configuración del gráfico
fig.update_layout(
    title='Comparación porcentual por género y etapa',
    polar=dict(
        radialaxis=dict(visible=True, range=[40, 55])
    ),
    template='plotly_dark',
    showlegend=True,
    height=600,
    width=800
)

fig.show()

"""# Inteligencia Artificial

Este código sirve para predecir y visualizar tendencias de equilibrio de género a partir de los datos históricos de inscripción, apoyando el análisis y la toma de decisiones en temas de igualdad y participación femenina.
"""

# 1) Crear una sola base de datos
df_all = Base_inscritos[['AÑO', 'PROGRAMA ACADÉMICO', 'SEXO', 'INSCRITOS']]

# 2) Calcular total de mujeres por año y programa
df_mujeres = (
    df_all[df_all['SEXO'] == 'Mujer']
    .groupby(['AÑO', 'PROGRAMA ACADÉMICO'])['INSCRITOS']
    .sum()
    .reset_index(name='Mujeres')
)

# 3) Calcular total general por año y programa
df_total = (
    df_all.groupby(['AÑO', 'PROGRAMA ACADÉMICO'])['INSCRITOS']
    .sum()
    .reset_index(name='Total')
)

# 4) Unir ambos dataframes
df_union = pd.merge(df_mujeres, df_total, on=['AÑO', 'PROGRAMA ACADÉMICO'], how='left').fillna(0)

# 5) Calcular el porcentaje de mujeres
df_union['PORCENTAJE MUJERES'] = (df_union['Mujeres'] / df_union['Total']) * 100

# 6) variables predictoras
# Use the calculated 'PORCENTAJE MUJERES' as the target variable
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(df_union[['PORCENTAJE MUJERES']]) # Use 'PORCENTAJE MUJERES' as feature for now, potentially add more features later
y = df_union['PORCENTAJE MUJERES'] # Set 'PORCENTAJE MUJERES' as the target variable


#7) dividir entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Manually split training data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)


#8) Modelo de red neuronal
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(16, input_dim=X_train.shape[1], activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='linear')  # salida: porcentaje estimado
])


#9) grafico

# 1. Entrenar el modelo
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
history = model.fit(X_train, y_train, epochs=100, batch_size=8, validation_data=(X_val, y_val), verbose=0)

# 2. Generar las predicciones
y_pred = model.predict(X_test).flatten()   # Asegúrate de ejecutar esto justo después de entrenar

# 3. Crear gráfico interactivo con Plotly
import plotly.graph_objects as go

fig = go.Figure()

  # 3.1 Línea de valores reales
fig.add_trace(go.Scatter(
      x=list(range(len(y_test))),
      y=y_test.values,
      mode='lines+markers',
      name='Real',
      marker=dict(color='orange', size=8),
      line=dict(width=2),
      hovertemplate='Caso %{x}<br>Valor real: %{y:.2f}%<extra></extra>' # Added % to hover template
  ))

# Línea de valores predichos
fig.add_trace(go.Scatter(
    x=list(range(len(y_pred))),
    y=y_pred,
    mode='lines+markers',
    name='Predicho',
    marker=dict(color='steelblue', size=8),
    line=dict(width=2, dash='dot'),
    hovertemplate='Caso %{x}<br>Valor predicho: %{y:.2f}%<extra></extra>' # Added % to hover template
))

# Configuración general del gráfico
fig.update_layout(
    title="Comparación interactiva de tendencia real vs predicha (Red Neuronal)",
    xaxis_title="Casos (programas/años)",
    yaxis_title="Porcentaje de mujeres (%)",
    template="plotly_white",
    hovermode="x unified",
    legend=dict(title="Tipo de valor"),
    width=850,
    height=500
)

fig.show()